name: Deploy PROD to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            APP_DIR=/home/adminio/htdocs/lapsi.online
            PROC_NAME=piopi-prod
            PORT=3000

            echo "📦 Déploiement en production sur $APP_DIR"

            # Vérifie que le dossier existe
            if [ ! -d "$APP_DIR" ]; then
              echo "❌ Le dossier $APP_DIR n'existe pas sur le VPS"
              exit 1
            fi

            cd "$APP_DIR"

            # Récupère le dernier code depuis main
            git fetch origin main
            git reset --hard origin/main

            # Charge Node/NPM (via nvm si présent)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use --lts >/dev/null 2>&1 || true

            echo "✅ Node version : $(node -v)"
            echo "✅ NPM version : $(npm -v)"

            # Build du projet
            npm ci
            npm run build

            # Redémarre le process PM2
            if ! command -v pm2 >/dev/null 2>&1; then npm install -g pm2; fi
            if ! command -v serve >/dev/null 2>&1; then npm install -g serve; fi

            pm2 delete $PROC_NAME || true
            pm2 start "serve -s ./dist -l $PORT" --name $PROC_NAME
            pm2 save

            echo "✅ Déploiement terminé avec succès !"
