name: Deploy PROD to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            APP_DIR=/home/adminio/htdocs/lapsi.online
            PROC_NAME=piopi-prod
            PORT=3001

            # utiliser Node/NPM système pour éviter les soucis PATH
            which node
            which npm
            node -v
            npm -v

            cd "$APP_DIR"
            git fetch origin main
            git reset --hard origin/main

            npm ci
            npm run build

            if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2; fi
            if ! command -v serve >/dev/null 2>&1; then npm i -g serve; fi

            pm2 delete "$PROC_NAME" || true
            pm2 start "serve -s ./dist -l $PORT" --name "$PROC_NAME"
            pm2 save

            # si sudo nginx -t demande un mot de passe, garde seulement le reload laissé à l'UI CloudPanel
            # sudo nginx -t && sudo systemctl reload nginx
